# Site settings
title: Jianyu Zhang (JaYzZ95)
header-img: "img/green.jpg"
tagline: "cn"  
description: “张鉴宇"  
baseurl: ""
url: "http://jayzz”  

# About/contact
owner: 
  name: " JaYzZ”
  email: zhangjianyu1995@gmail.com
  bio: “Ready, Steady, Start”

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  
twitter_username: JaYzzZ95
github_username: JaYzZ
facebook_username: 张鉴宇
weibo_username: JaY_zZ
zhihu_username: JaYzZ

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: North America/New York

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: “JaYzZ”
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : 
  disqus :
      short_name : 

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
